
package com.sunyard.enums;

/*
 * 数据字典主键集合
 * K_DPTSTT--部门状态；K_DPTLVL--部门级别;K_USERSTT--用户状态;K_USERTYPE--用户类型
 * K_CERTTYPE--证件类型;K_RESTYPE--资源类型;K_RESSTT--资源状态;K_PLATTYPE--平台类型;K_PARAMTYPE--系统参数类型;K_PRODTYPE--产品类型;K_PRECISIONDESC--精度方向
 * SIM_OPERATORS--SIM卡运营商;SIM_AUTHOR--SIM卡开发人员;SIM_FINAL_AT--SIM卡最后归属人;SIM_FINAL_ACTION--最后动作
 */
public enum DICTKEY {
	K_DPTSTT,K_DPTLVL,K_USERSTT,K_USERTYPE,
	K_CERTTYPE,K_RESTYPE,K_RESSTT,K_PLATTYPE,K_PARAMTYPE,K_PRODTYPE,K_PRECISIONDESC,

	SIM_OPERATORS,SIM_AUTHOR,SIM_FINAL_AT,SIM_FINAL_ACTION
	;

}
